#
#This document contains the setting information of this blog, you can edit it to personalize your blog,
#

# Your blog name, you want to replace with a blog name "Biswadip", the following modifications can be similarly treated
# Note, "name: Biswadip", a space after the colon can not be omitted.
# Behind the pound sign text is documentation, it will not be read by the program.

# Description/Signature
name: বিস্বদীপ
description : Personal Blog


#
#The following settings are optional
#

#URL of your blog logo image, the recommended size is not more than 300px × 300px
avatar: https://raw.githubusercontent.com/mandalbiswadip/mandalbiswadip.github.io/master/images/logo.png

# Your favicon picture URL (appears in the browser tab), we recommend the use of a smaller (64px × 64px) Picture
favicon: https://raw.githubusercontent.com/mandalbiswadip/mandalbiswadip.github.io/master/images/favicon.png


# Menu button
navigation:
  - name : Home
    url: /
  - name : About
    url: /about
  - name : Music
    url: /music
# Per page Posts
paginate: 8

# Introduction The distinguishing mark
excerpt_separator: <!-- more -->

# Your social network links, they will appear as an icon in the footer of your website, fill out the optional
footer-links:
  email: mandalbiswadip448@gmail.com
  facebook: #https://www.facebook.com/<>
  github: mandalbiswadip #https://github.com/<>
  instagram: mandalbiswadip #https://instagram.com/<>
  linkedin: mandalbiswadip #https://www.linkedin.com/in/<>
  stackoverflow: # http://stackoerflow.com/<>
  twitter: biswadipmandal2 # https://www.twitter.com/<your_twitter_username>


# Site footer text
footer-text : Copyright (c) 2019

#
# Comment, note that you should not add many different comments area
#

# Input Disqus shortname, you can add a comment area
disqus: http-mandalbiswadip-github-io #shortname

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Input Gitalk related settings, you can add a comment area, specific look tutorial
gitalk:
  clientID:
  clientSecret :
  repo:
  owner:

# Enter the Google Analytics web tracking code
google_analytics: true


#
# !! All the following settings do not need to be changed!!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


theme: jekyll-theme-cayman
